name: calculo_saque_aniversario
description: Aplicativo para cálculo do saque aniversário.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  extended_masked_text: ^2.3.1
  month_year_picker: ^0.1.0+1
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/icon_app.png'

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/work_sans/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/work_sans/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/work_sans/WorkSans-Bold.ttf
          weight: 700
